# Generated by Django 4.0.1 on 2022-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('Comand', models.CharField(max_length=150, verbose_name='Команда')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Місце народження')),
                ('place_now', models.CharField(max_length=150, verbose_name='Місце проживання')),
                ('growth', models.CharField(max_length=50, verbose_name='Ріст')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('started_playing', models.CharField(max_length=50, verbose_name='Почав грати')),
                ('goals_scored', models.IntegerField(verbose_name='Забиті голи')),
                ('transfer_head', models.IntegerField(verbose_name='Передачі головою')),
                ('own_goals', models.IntegerField(verbose_name='Автоголи')),
                ('yellow_cards', models.IntegerField(verbose_name='Жовті карточки')),
                ('red_cards', models.IntegerField(verbose_name='Червоні карточки')),
                ('goals_from_the_penalty_spot', models.IntegerField(verbose_name='Голи з пенальті')),
                ('average_time_on_the_field', models.CharField(max_length=50, verbose_name='Час на полі')),
                ('number_of_games_played', models.IntegerField(verbose_name='Кількість зіграних ігор')),
                ('replaced', models.IntegerField(verbose_name='Вийшов на заміну')),
                ('number_of_replacements', models.IntegerField(verbose_name='Кількість замін')),
                ('facts', models.TextField(verbose_name='Факти')),
                ('images', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Ігроки',
                'verbose_name_plural': 'Ігроки',
            },
        ),
    ]
