# Generated by Django 4.0.1 on 2022-02-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='number_of_games_played',
        ),
        migrations.RemoveField(
            model_name='model',
            name='number_of_replacements',
        ),
        migrations.RemoveField(
            model_name='model',
            name='replaced',
        ),
    ]
