# Generated by Django 4.0.1 on 2022-02-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_model_number_of_games_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='images',
            field=models.ImageField(upload_to='photos/%Y/%m/%/d/'),
        ),
    ]
