# Generated by Django 4.0.1 on 2022-02-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_model_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='images',
            field=models.URLField(),
        ),
    ]
